// web/src/shared/pages/auth/sign-in.tsx
"use client";

import useProfile from "@/shared/hooks/use-profile";
import { useMutation } from "@apollo/client";
import { LOGIN_USER } from "@/shared/graphql/actions/login.action";
import { Input } from "@/shared/components/ui/input";
import Cookies from "js-cookie";
import { useState } from "react";
import { Button } from "@/shared/components/ui/button";
import useUser from "@/shared/hooks/use-user";
import { redirect } from "next/navigation";

const SignInPage = () => {
  const [login, { loading: signInLoading }] = useMutation(LOGIN_USER);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const profile = useProfile({ name: "nikita" });
  const user = useUser();

  if (profile.loading && user.loading) {
    return "Loading...";
  }

  if (signInLoading) {
    return "Signing...";
  }

  if (user.user?.name) {
    redirect("/");
  }

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const res = await login({ variables: { email, password } });

    console.log(profile);
    if (res.data.login.error) return;

    console.log(res.data.login.refreshToken)
    console.log(res.data.login.accessToken)

    Cookies.set("refresh_token", res.data.login.refreshToken, {
      domain: "localhost",
    });
    Cookies.set("access_token", res.data.login.accessToken, {
      domain: "localhost",
    });

    location.reload()
  };

  return (
    <div className="h-[calc(100vh-3rem)] w-full flex items-center justify-center">
      <form
        onSubmit={handleSubmit}
        className="
        w-[25rem]
        h-[260px]
        flex
        flex-col
        gap-4
        border
        p-4
        rounded-lg
        justify-center
        shadow
        "
      >
        <h2 className="flex flex-col text-xl text-center">Sign In</h2>
        <Input
          placeholder="email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <Input
          placeholder="password"
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <Button type="submit">Sign In</Button>
      </form>
    </div>
  );
};

export default SignInPage;

// admin/src/app/sign-in/sign-in.component.ts
import {
  Component,
  OnDestroy,
  OnInit,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { MyButtonComponent } from '../../components/my-button/my-button.component';
import { Apollo } from 'apollo-angular';
import { MyLoaderComponent } from '../../components/my-loader/my-loader.component';
import { UserService } from '../services/user/user.service';
import { User } from '../../types/user.type';
import { Router } from '@angular/router';
import { LOGIN_USER } from '../../graphql/login.action';
import { MyInputComponent } from '../../components/my-input/my-input.component';

@Component({
  selector: 'app-sign-in',
  standalone: true,
  imports: [RouterLink, MyButtonComponent, MyLoaderComponent, MyInputComponent],
  templateUrl: './sign-in.component.html',
})
export class SignInComponent implements OnDestroy, OnInit {
  public querySubscription?: Subscription;
  public data?: any;
  public loading?: boolean = false;
  public user: User | null = null;
  public emailValue: string = '';
  public passwordValue: string = '';
  private userSubscription: Subscription | unknown;
  private isAuthenticatedSubscription: Subscription | unknown;

  constructor(
    private apollo: Apollo,
    private userService: UserService,
    private router: Router
  ) {}

  onEmailChange(value: string) {
    this.emailValue = value;
  }

  onPasswordChange(value: string) {
    this.passwordValue = value;
  }

  SignIn() {
    const email = this.emailValue;
    const password = this.passwordValue;
    this.loading = true;

    this.querySubscription = this.apollo
      .mutate<any>({
        mutation: LOGIN_USER,
        variables: {
          email: email,
          password: password,
        },
      })
      .subscribe(({ data }) => {
        this.data = data.login;
        this.loading = false;

        if (this.data.accessToken && this.data.refreshToken) {
          localStorage.setItem('accessToken', this.data.accessToken);
          localStorage.setItem('refreshToken', this.data.refreshToken);
          this.userService.initUser$();
          location.reload();
        }

        return;
      });
  }

  ngOnInit(): void {
    this.isAuthenticatedSubscription = this.userService
      .isAuthenticated$()
      .subscribe((isAuthenticated) => {
        if (isAuthenticated) {
          this.router.navigate(['/users']);
        }
        console.log(isAuthenticated);
      });

    this.userService.initUser$();
  }

  ngOnDestroy(): void {
    this.querySubscription?.unsubscribe();
  }
}

@if (loading) {
<div class="relative h-screen">
  <div
    class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center"
  >
    <my-loader></my-loader>
    <h2 class="mt-4">Loading Data...</h2>
  </div>
</div>
} @else {
<div class="h-full flex items-center justify-center text-center">
  <div class="flex flex-col h-[250px] w-[400px] border p-3 rounded-lg shadow justify-center">
    <h1>Sign in to the System</h1>
    <div class="p-3 flex flex-col gap-2">
      <my-input
        placeholder="email"
        (inputChange)="onEmailChange($event)"
        type="email"
      ></my-input>
      <my-input
        placeholder="password"
        type="password"
        (inputChange)="onPasswordChange($event)"
      ></my-input>
    </div>
    <my-button (click)="SignIn()" text="Sign In"></my-button>
  </div>
</div>
}
